config-version: 2

name: "ethereum"
version: "1.0.0"
profile: "dbt_ethereum"

models:
  ethereum:
    nft:
      +schema: nft
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_nft

    nft_metadata:
      +schema: nft_metadata

    labels:
      +schema: labels
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_labels

    index:
      +schema: index
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_index

    otherdeed:
      +schema: otherdeed
      +tags:
        - chain_ethereum
        - level_modeling      
        - proj_otherdeed

seeds:
  ethereum:
    nft:
      +schema: nft

vars:
  prices_usd: "prices.usd"
  start_ts: "1970-01-01"
  end_ts: "9999-01-01"
