config-version: 2

name: "ethereum"
version: "1.0.0"
profile: "dbt_ethereum"

models:
  ethereum:
    nft:
      +schema: nft
      +materialized: view
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_nft
    nft_metadata:
      +schema: nft_metadata
      +materialized: view      
    labels:
      +schema: labels
      +materialized: view
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_labels

seeds:
  ethereum:
    nft:
      +schema: nft

vars:
  prices_usd: "prices.usd"
  start_ts: "1970-01-01"
  end_ts: "9999-01-01"
