version: 2

models:
  - name: nft_trades
    config:
      materialized: table
    alias: trades
  - name: nft_mints
    config:
      materialized: table
    alias: mints
  - name: opensea_wyvern_atomic_match
    config:
      materialized: view
  - name: opensea_trades
    config:
      materialized: view
  - name: cryptopunks_trades
    config:
      materialized: view
  - name: nft_mint_erc721
    config:
      materialized: ephemeral
  - name: nft_mint_erc1155
    config:
      materialized: ephemeral
