version: 2

models:
  - name: wyvern_data
    config:
      materialized: view
  - name: opensea_trades
    config:
      materialized: ephemeral
  - name: nft_trades
    config:
      materialized: table
      file_format: parquet
  - name: nft_tokens
    config:
      materialized: view
  - name: nft_token_metadata
    config:
      materialized: view
  - name: cryptopunks_trades
    config:
      materialized: table
      file_format: parquet
  - name: nft_mint_erc721
    config:
      materialized: ephemeral
  - name: nft_mint_erc1155
    config:
      materialized: ephemeral
  - name: nft_mints
    config:
      materialized: table
      file_format: parquet
      