version: 2

models:
  - name: wyvern_data
    config:
      materialized: view
  - name: opensea_trades
    config:
      materialized: ephemeral
  - name: nft_trades
    config:
      materialized: table
    alias: trades
  - name: nft_tokens
    config:
      materialized: view
    alias: tokens
  - name: cryptopunks_trades
    config:
      materialized: table
  - name: nft_mint_erc721
    config:
      materialized: ephemeral
  - name: nft_mint_erc1155
    config:
      materialized: ephemeral
  - name: nft_mints
    config:
      materialized: table
    alias: mints
      